require 'fileutils'

module Ignore
  class Gitignore
    
    def initialize
      @path = File.join(Dir.pwd(),'.gitignore')
    end

    def append( content , lang = "" )
      FileUtils.touch @path
      data="#\n#AutoGenerated #{lang} Gitignore\n#\n"+content+"\n##\n"
      File.open(@path, 'a'){|f| f.write(data) }
      Command.output "Updated .gitignore"
    end

    def read
      return File.open(@path,'r'){|f| f.read } if exists? 
      ""
    end

    def exists?
      File.exists?( @path )
    end

    def path
      @path
    end
  end
end
